#+Title: Starter Kit G-Client
#+OPTIONS: toc:nil num:nil ^:nil
#+Babel: :exports code :tangle no

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

G-Client is part of T.V. Raman's [[http://code.google.com/p/emacspeak/][emacspeak]] package which provides for
interaction with Google services (e.g., google-docs, google-calendar)
from within Emacs.

* Installation
  :PROPERTIES:
  :results:  silent
  :CUSTOM_ID: instillation
  :END:

1. Grab the latest version of G-Client by running the following in
   this directory.
   #+BEGIN_SRC sh
     cd src/
     svn co http://emacspeak.googlecode.com/svn/trunk/lisp/g-client/
   #+END_SRC

2. The in the =g-client= directory run the following commands to build
   the package.
   #+BEGIN_SRC sh
     cd src/g-client
     make
   #+END_SRC

3. Add the =g-client= directory to the load path, and load the package
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path
                  (expand-file-name
                   "g-client"
                   (expand-file-name
                    "src"
                    (file-name-directory
                     (or load-file-name (buffer-file-name))))))
     (load-library "g")
   #+END_SRC

4. Finally, in the current version of g-client one small change to the
   code is required.  In the definition `[[file:src/g-client/gdocs.el::(defun%20gdocs-publish-from-org%20()][gdocs-publish-from-org]]' the
   call to the `org-export-region-as-html' function should be changed
   from
   #+BEGIN_SRC emacs-lisp :tangle no
     (org-export-region-as-html (point-min) (point-max)
                                nil g-scratch-buffer)
   #+END_SRC
   to
   #+BEGIN_SRC emacs-lisp :tangle no
     (org-export-region-as-html (point-min) (point-max)
                                'body-only g-scratch-buffer)
   #+END_SRC
   so that the exported html only includes the body of the html
   document.  The header information generated by Org-mode seems to
   confuse google documents.

For more information see
- the [[usage]] section immediately below
- the file:src/g-client/g-client.org file included with =g-client=
- and this blog post [[http://blog.vivekhaldar.com/post/1649745633/editing-google-docs-in-emacs][blog.vivekhaldar.com/editing-google-docs-in-emacs]]

* Usage
  :PROPERTIES:
  :CUSTOM_ID: usage
  :END:
Usage is as simple as

1. add g-client to your load path
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path (expand-file-name
                              "g-client" (expand-file-name "src" starter-kit-dir)))
   #+END_SRC

2. load g-client
   #+BEGIN_SRC emacs-lisp
     (load-library "g")
   #+END_SRC

3. sign into google documents with =M-x gdocs-sign-in=

4. open an Emacs buffer which you would like to post to google docs

5. publish the buffer with `gdocs-publish-from-text'
