#+TITLE: Starter Kit Window
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Window
** Window default settings
Settings in relation with emacs window behavior[1].
#+BEGIN_SRC emacs-lisp
  (setq frame-title-format '(buffer-file-name "%b [%f]" "%b"))

  (tool-bar-mode   -1)
  (scroll-bar-mode -1)
  (menu-bar-mode   -1)
  (tooltip-mode    -1)

  (setq inhibit-startup-screen                t
        inhibit-startup-message               t
        line-number-mode                      t
        column-number-mode                    t
        icomplete-mode                        t
        read-buffer-completion-ignore-case    t
        read-file-name-completion-ignore-case t
        color-theme-is-global                 t
        save-place                            t)
#+END_SRC

** Color themes
*** Emacs24 =deftheme=
Emacs24 has build in support for saving and loading themes.

A Theme builder is available at http://elpa.gnu.org/themes/ along with
a list of pre-built themes at http://elpa.gnu.org/themes/view.html and
themes are available through ELPA.

Downloaded themes may be saved to the =themes/= directory in the base
of the starter kit which ignored by git. Once downloaded and
evaluated a theme is activated using the =load-theme= function.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path (concat starter-kit-dir "/themes"))
  (add-to-list 'custom-theme-load-path (concat starter-kit-dir "/themes"))
  (setq custom-safe-themes t)
#+END_SRC

*** Custom solarized theme
#+BEGIN_SRC emacs-lisp
  (use-package solarized-theme
    :custom
    ;; make the fringe stand out from the background
    ;;(solarized-distinct-fringe-background t)

    ;; Don't change the font for some headings and titles
    (solarized-use-variable-pitch nil)

    ;; make the modeline high contrast
    (solarized-high-contrast-mode-line t)

    ;; Use less bolding
    ;;(solarized-use-less-bold t)

    ;; Use more italics
    ;;(solarized-use-more-italic t)

    ;; Use less colors for indicators such as git:gutter, flycheck and similar
    (solarized-emphasize-indicators nil)

    ;; Don't change size of org-mode headlines (but keep other size-changes)
    (solarized-scale-org-headlines nil)

    ;; Change the size of markdown-mode headlines (off by default)
    (solarized-scale-markdown-headlines t)

    ;; Avoid all font-size changes
    (solarized-height-minus-1 1.0)
    (solarized-height-plus-1 1.0)
    (solarized-height-plus-2 1.0)
    (solarized-height-plus-3 1.0)
    (solarized-height-plus-4 1.0)

    ;; Highlight all numbers
    (solarized-highlight-numbers t)

    (x-underline-at-descent-line t)  
    :config
    (load-theme 'solarized-light t)
    (custom-set-faces
     '(org-block-begin-line ((t (:overline nil :underline nil))))
     '(org-block-end-line ((t (:overline nil :underline nil))))
     '(mu4e-header-face ((t (:inherit font-lock-comment-face))))
     '(mu4e-unread-face ((t (:foreground "#dc322f" :weight bold))))
     )
    )
#+END_SRC

*** Sleek modeline
#+BEGIN_SRC emacs-lisp
  (use-package sleek-modeline
    :ensure t
    :after solarized-theme       
    :custom
    (sleek-modeline-size 'medium)
    (sleek-modeline-background "#434B5A") 
    :config
    (sleek-modeline-mode 1))
#+END_SRC

*** Nerd icons font
#+BEGIN_SRC emacs-lisp
  (use-package nerd-icons
    :ensure t
    ;; :custom
    ;; The Nerd Font you want to use in GUI
    ;; "Symbols Nerd Font Mono" is the default and is recommended
    ;; but you can use any other Nerd Font if you want
    ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
  )
#+END_SRC

In order to get the needed font, run this code
#+BEGIN_SRC emacs-lisp :tangle no
  ;; Linux/macOS/BSDs
  (when (member system-type '(gnu gnu/linux gnu/kfreebsd darwin))
    (unless (find-font (font-spec :name "Symbols Nerd Font Mono"))
      (nerd-icons-install-fonts t)))

  ;; Windows
  (when (string-equal system-type 'windows-nt)
    (unless (find-font (font-spec :name "Symbols Nerd Font Mono"))
      (nerd-icons-install-fonts "c:/Users/username/Desktop/")))

  ;; All-in-one
  ;; This will install in the default fonts folder for Linux/macOS/BSDs
  ;; (same as “t”), but for Windows this will download to the specified
  ;; folder
  (unless (find-font (font-spec :name "Symbols Nerd Font Mono"))
    (nerd-icons-install-fonts "c:/Users/username/Desktop/"))
#+END_SRC

** UI settings
*** Use space for tabulation
#+BEGIN_SRC emacs-lisp
  (set-default 'indent-tabs-mode nil)
#+END_SRC

*** Indicate empty lines
#+BEGIN_SRC emacs-lisp
  (set-default 'indicate-empty-lines t)
#+END_SRC

*** Fringe size
#+BEGIN_SRC emacs-lisp
;;(setq-default left-fringe-width 5)
#+END_SRC
** Setting default directories

First, set the temporary directory name and create it if it does not already
exist.
#+BEGIN_SRC emacs-lisp
  (setq temporary-file-directory     (concat starter-kit-dir "/tmp/"))
  (unless (file-exists-p temporary-file-directory)
    (make-directory temporary-file-directory))
#+END_SRC

Define several place where temporary files will be stored. For instance,
[[http://www.emacswiki.org/emacs/SavePlace][SavePlace]] stores the position where the point was at the last visit of a given
file. =backup-directory-alist= is related to the directory where emacs backup
file will be stored.
#+BEGIN_SRC emacs-lisp
  (setq save-place-file              (concat temporary-file-directory "places"))
  (setq recentf-save-file            (concat temporary-file-directory "recentf"))
  (setq smex-save-file               (concat temporary-file-directory "smex-items"))
  (setq ido-save-directory-list-file (concat temporary-file-directory "ido.last"))
  (setq ac-comphist-file             (concat temporary-file-directory "ac-comphist.dat"))
  (setq auto-save-list-file-prefix   (concat temporary-file-directory "auto-save-list/" ".auto-saves-"))
  (setq auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))
  (setq backup-directory-alist         `(("." . ,(concat temporary-file-directory "backups"))))
#+END_SRC

Automatically save and restore sessions
#+BEGIN_SRC emacs-lisp
  (setq desktop-dirname             (concat temporary-file-directory "session")
        desktop-base-file-name      "emacs.desktop"
        desktop-base-lock-name      "lock"
        desktop-path                (list desktop-dirname)
        desktop-save                t
        desktop-files-not-to-save   "^$" ;reload tramp paths
        desktop-restore-frames      nil
        desktop-load-locked-desktop nil)
  (unless (file-exists-p desktop-dirname)
    (make-directory desktop-dirname))
  (desktop-save-mode 0)
#+END_SRC

** UTF8 everywhere
#+BEGIN_SRC emacs-lisp
  (set-terminal-coding-system    'utf-8)
  (set-keyboard-coding-system    'utf-8)
  (prefer-coding-system          'utf-8)
  (set-buffer-file-coding-system 'utf-8)
#+END_SRC

** Uniquify settings
Change buffer name in case of various same name buffer
previously : Makefile and Makefile<2>
now        : Makefile|directory1 Makefile|directory2
#+BEGIN_SRC emacs-lisp
  (require 'uniquify)
  (setq uniquify-buffer-name-style 'reverse)
  (setq uniquify-separator "|")
  (setq uniquify-after-kill-buffer-p t) ; rename after killing uniquified
  (setq uniquify-ignore-buffers-re "^\\*") ; don't muck with special buffers
#+END_SRC

** Dired customization
*** Using 'a' to open a directory in the same buffer
#+BEGIN_SRC emacs-lisp
  (put 'dired-find-alternative-file 'disabled nil)
#+END_SRC

*** Make dired less verbose
#+BEGIN_SRC emacs-lisp
  (require 'dired-details)
  (setq-default dired-details-hidden-string "--- ")
  (dired-details-install)
#+END_SRC

*** Refresh also dired buffer
From [[http://whattheemacsd.com/sane-defaults.el-01.html][Magnars blog]]
#+BEGIN_SRC emacs-lisp
  (setq global-auto-revert-non-file-buffers t)
  (setq auto-revert-verbose nil)
#+END_SRC

*** Activate =hl-line= minor mode
#+BEGIN_SRC emacs-lisp
  (add-hook 'dired-mode-hook
            (lambda ()
              (hl-line-mode t)))
#+END_SRC

*** Jump to a file with =ido=
#+BEGIN_SRC emacs-lisp
  (define-key dired-mode-map "i" 'ido-find-file)
#+END_SRC
*** Files size

#+BEGIN_SRC emacs-lisp
  (defun dired-get-size ()
    (interactive)
    (let ((files (dired-get-marked-files)))
      (with-temp-buffer
        (apply 'call-process "/usr/bin/du" nil t nil "-sch" files)
        (message
         "Size of all marked files: %s"
         (progn
           (re-search-backward "\\(^[0-9.,]+[A-Za-z]+\\).*total$")
           (match-string 1))))))
  (define-key dired-mode-map (kbd "z") 'dired-get-size)
#+END_SRC
*** Dired subtree
#+BEGIN_SRC emacs-lisp
  (require 'dired-subtree)
  (define-key dired-mode-map "+" 'dired-subtree-insert)
  (define-key dired-mode-map "-" 'dired-subtree-remove)
#+END_SRC

** Ibuffer customization
Use human readable size column (from [[http://www.emacswiki.org/emacs/IbufferMode#toc12][coldnew]])
#+BEGIN_SRC emacs-lisp
  (define-ibuffer-column size-h
    (:name "Size")
    (cond
     ((> (buffer-size) 1000)    (format "%7.1fk" (/ (buffer-size) 1000.0)))
     ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
     (t  (format "%8d" (buffer-size)))))

  (setq
   ibuffer-default-sorting-mode 'filename/process
   ibuffer-eliding-string "…"
   ibuffer-compile-formats t
   ibuffer-formats '((mark modified read-only
                           " " (name 25 25 :left :elide)
                           " " (size-h 9 -1 :right)
                           " " (mode 7 7 :left :elide)
                           ;;" " (git-status 8 8 :left)
                           " " filename-and-process)
                     (mark " " (name 16 -1) " " filename))
   ibuffer-show-empty-filter-groups nil
   ibuffer-saved-filter-groups
   (quote (("default"
            ("c++" (mode . c++-mode))
            ("shell script" (mode . sh-mode))
            ("emacs lisp" (mode . emacs-lisp-mode))
            ("python" (mode . python-mode))
            ("LaTeX" (or
                      (mode . latex-mode)
                      (mode . LaTeX-mode)
                      (mode . tex-mode)))
            ("ruby" (mode . ruby-mode))
            ("java-script" (or
                            (mode . js-mode)
                            (mode . js2-mode)))
            ("java" (mode . java-mode))
            ("html" (or
                     (mode . html-mode)
                     (mode . web-mode)
                     (mode . haml-mode)))
            ("xml" (mode . nxml-mode))
            ("css" (mode . css-mode))
            ("org agenda"  (mode . org-agenda-mode))
            ("org" (or
                    (mode . org-mode)
                    (name . "^\\*Calendar\\*$")
                    (name . "^diary$")))
            ("text misc" (or
                          (mode . text-mode)
                          (mode . rst-mode)
                          (mode . markdown-mode)))
            ("w3m" (mode . w3m-mode))
            ("git" (or
                    (mode . magit-log-edit-mode)
                    (mode . magit-log)))
            ("dired" (mode . dired-mode))
            ("help" (or
                     (mode . Info-mode)
                     (mode . help-mode)
                     (mode . Man-mode)))
            ("*buffer*" (name . "\\*.*\\*"))))))
  (add-hook 'ibuffer-mode-hook
            #'(lambda ()
                (hl-line-mode t)
                (ibuffer-switch-to-saved-filter-groups "default")))
#+END_SRC
** Buffer scrolling
Smooth keyboard scrolling
#+BEGIN_SRC emacs-lisp
  (setq
   redisplay-dont-pause t                 ;; scrolling
   scroll-step 1                          ;; scroll line per line (1 line instead of 3)
   scroll-margin 0                        ;; do smooth scrolling, ...
   scroll-conservatively 100000           ;; ... the defaults ...
  ;; scroll-up-aggressively 0               ;; ... are very ...
  ;;  scroll-down-aggressively 0             ;; ... annoying
   auto-window-vscroll nil
   )
#+END_SRC

Use [[https://github.com/kiwanami/emacs-inertial-scroll][inertial-scroll]] for a really smooth scrolling when using mouse wheel and
next/prior keys.
#+BEGIN_SRC emacs-lisp
  (require 'inertial-scroll)
  (inertias-global-minor-mode 1)
  (setq inertias-rebound-flash nil
        inertias-initial-velocity-wheel 20)
  (global-set-key [(mouse-5)] 'inertias-up-wheel)
  (global-set-key [(mouse-4)] 'inertias-down-wheel)
  (global-set-key (kbd "<next>")  'inertias-up)
  (global-set-key (kbd "<prior>") 'inertias-down)
#+END_SRC

** Naked emacs
From [[http://bzg.fr/emacs-strip-tease.html]]

*** Hide modeline
From [[http://bzg.fr/emacs-hide-mode-line.html]]
#+BEGIN_SRC emacs-lisp
  (defvar-local sk-hidden-mode-line-mode nil)

  (define-minor-mode sk-hidden-mode-line-mode
    "Minor mode to hide the mode-line in the current buffer."
    :init-value nil
    :global nil
    :variable sk-hidden-mode-line-mode
    :group 'editing-basics
    (if sk-hidden-mode-line-mode
        (setq hide-mode-line mode-line-format
              mode-line-format nil)
      (setq mode-line-format hide-mode-line
            hide-mode-line nil))
    (force-mode-line-update)
    ;; Apparently force-mode-line-update is not always enough to
    ;; redisplay the mode-line
    (redraw-display)
    (when (and (called-interactively-p 'interactive)
               sk-hidden-mode-line-mode)
      (run-with-idle-timer
       0 nil 'message
       (concat "Hidden Mode Line Mode enabled.  "
               "Use M-x sk-hidden-mode-line-mode to make the mode-line appear."))))
#+END_SRC

*** Big fringe
#+BEGIN_SRC emacs-lisp
  (defvar sk-big-fringe-mode nil)
  (define-minor-mode sk-big-fringe-mode
    "Minor mode to hide the mode-line in the current buffer."
    :init-value nil
    :global t
    :variable sk-big-fringe-mode
    :group 'editing-basics
    (if (not sk-big-fringe-mode)
        (set-fringe-style nil)
      (set-fringe-mode
       (/ (- (frame-pixel-width)
             (* 100 (frame-char-width)))
          2))))

  ;; Get rid of the indicators in the fringe
  (mapcar (lambda(fb) (set-fringe-bitmap-face fb 'org-hide))
          fringe-bitmaps)
#+END_SRC
*** Shortcut
#+BEGIN_SRC emacs-lisp
  (defun sk-naked-emacs ()
    (interactive)
    (progn
      (if (not sk-hidden-mode-line-mode)
          (sk-hidden-mode-line-mode 1)
        (sk-hidden-mode-line-mode 0))
      (if (not sk-big-fringe-mode)
          (sk-big-fringe-mode 1)
        (sk-big-fringe-mode 0))
      ))
  (global-set-key (kbd "C-s-SPC") 'sk-naked-emacs)
#+END_SRC

** Hide =async-shell-command= buffer
#+BEGIN_SRC emacs-lisp
  (add-to-list 'display-buffer-alist '("^*Async Shell Command*" . (display-buffer-no-window)))
#+END_SRC
** Copy text selected with the mouse
#+BEGIN_SRC emacs-lisp
  (setq mouse-drag-copy-region t)
  (setq save-interprogram-paste-before-kill t)
#+END_SRC
** Misc.
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC


* Footnotes

[1] [[http://whattheemacsd.com/init.el-01.html][Magnars]] suggests to place all the UI stuff deactivation
(=tool-bar=, =scroll-bar=) at the really beginning of the =init.el=
file. Not really conclusive especially when emacs server is used.
